### ISSUE TITLE
[Feature] Taking a csv and uploding it to have a faster test environment

### ISSUE THREAD

**Issue by eduardonard** [eduardonard/Blackjack-card-counter#2]
The csv should have only values of the cards that are already playes

**Comment by MaNiLu2** [comment]
can you assign me?

**Comment by eduardonard** [comment]
Sure! Thank you very much for contributing! The best csv should be like this:
```
link to the video, [minute]
3 4 5 7 10
3 3 5 9 6
```
just stop maybe 5 hands before the shuffle, and write the time

**Comment by eduardonard** [comment]
Closing as i implemented it
